### PR TITLE
Add more helpful error messages for single-argument types.

### PR DESCRIPTION
**Pull request by jkinkead**
It's really hard to figure out what you've done wrong if you type a bad number when Scallop expects one.

I also added helpful messages for URL / URI.

### CODE REVIEW

**Comment by Rogach** [comment]
I think it would be helpful to include actual supplied value in error messages, like `bad Int value: one` - makes for easier debugging. Can you patch `handler` to accept the supplied arguments as well?

P.S. I somehow only now found `identity` method - much cleaner, thanks!

**Comment by jkinkead** [comment]
`WrongOptionFormat` [overrides the exception message](https://github.com/scallop/scallop/blob/afd848f466e6ef38837179d54d74278ff8325888/src/main/scala/org.rogach.scallop/Exceptions.scala#L54) to include the provided argument. With this patch, scallop will print `Bad arguments for option 'foo': 'one' - bad Int value`.

It seems a little redundant to change that to `Bad arguments for option 'foo': 'one' - bad Int value: one`, but I'm happy to add it if you're sure that's what you want.

**Comment by Rogach** [comment]
No, you are right, that was a confusion on my part. Merging the PR.

**Comment by jkinkead** [comment]
Awesome, thanks!

**Pull request merged**
