### PR TITLE
Bump scala native to 0.4.0

### PR DESCRIPTION
**Pull request by vhiairrassary**
⚠️ Waiting for Scalatest `3.2.4`, currently using `3.2.4-M1`

### CODE REVIEW

**Comment by Rogach** [comment]
Great! Can you please also remove `+scallopNative/test:run` from ci.yml and release-checklist.txt?

**Comment by vhiairrassary** [comment]
Done 👍 I also added `scallopNative/test` to `.travis.yml` but I am wondering if Travis is still used or not?

**Comment by Rogach** [comment]
No, we don't use Travis, Github Actions should be enough (at least until it too dies from natural causes).

This PR is marked as a draft - do you plan something else, or can I merge it already?

P.S. It's great that we can now run tests for all platforms (JVM, JS, Native) using ScalaTest. The next step would be to move non-platform-specific tests from `jvm/src/test` into `src/test` - shouldn't be hard in most cases, just moving the files should be sufficient (anything that doesn't move cleanly is probably platform-specific and should remain in JVM subproject).

**Comment by vhiairrassary** [comment]
I removed `.travis.yml` file then. Regarding draft I was waiting scalatest `3.2.4` to be released, because I am currently relying on `3.2.4-M1`, hopefully it should be out soon 🤞

**Comment by Rogach** [comment]
I don't think we should be too picky about milestone version of ScalaTest - it's just a testing library after all, and the worst possible quite-unlikely thing that could happen is tests failing to detect regressions - but since we tested on stable version recently we should be reasonably covered.

I'd say that we merge this and get a new Scallop version out, so that we don't stall upgrades to 0.4 in dependent projects.

**Comment by vhiairrassary** [comment]
Sounds good for me, you can merge if you want

**Comment by Rogach** [comment]
Released in version `4.0.2`. Thank you!

**Pull request merged**
