### PR TITLE
reprocase issue #57

### PR DESCRIPTION
**Pull request by evantill**
reprocase for issue #57

### CODE REVIEW

**Comment by clhodapp** [comment]
You should probably repush with a better commit message if you intend your commit to be merged.

It should start with a capital letter, have a verb, and not use "reprocase".
An example would be: "Add (ignored) test case to reproduce issue #57"

There's also no reason to commit your .gitignore here.

**Comment by evantill** [comment]
Hi, thanks for your comment.
I will do better next time.

do what ever you want for the .gitignore (it contains only standard IntelliJ files generated by sbt)

I would also suggest to remove eclipses files (.project and .classpath)

**Comment by clhodapp** [comment]
You can still change it. Do you have command-line git set up?

**Comment by evantill** [comment]
yes

**Comment by clhodapp** [comment]
Great.

cd to your repository, make sure you are on the branch you used here, and do:

``` shell
git reset HEAD~
git add src/test/scala/ValueConverterTest.scala
git commit
<edit commit message>
git push --force
```

**Comment by clhodapp** [comment]
Sorry! Strike the --amend!

**Comment by evantill** [comment]
done without the amend

**Comment by clhodapp** [comment]
Looks wonderful. Sorry about the mixup with amend. It can be hard to get from point A to point B in git without a terminal in front of you.

**Comment by evantill** [comment]
no problems

**Pull request merged**
