### PR TITLE
native build wip

### PR DESCRIPTION
**Pull request by oker1**
Building the native package works.

Native tests are not working since scalatest is not yet built for it.
The JVM crossVersions are not working, it's only built for 2.12, I have no idea why.

### CODE REVIEW

**Comment by Rogach** [comment]
Great!

I'll look into it next week.

**Comment by Rogach** [comment]
Finally got to it! Sorry for making you wait so long.

First observation - I managed to cross-build the jvm part without problems, `+scallopJVM/test` worked for me.

**Comment by Rogach** [comment]
Second observation: I am unable to build the simplest example project. For example, the following:
```scala
// in scallop/shared/src/main/scala/org.rogach.scallop/Main.scala
package org.rogach.scallop
object Main {
  def main(args: Array[String]) {
    val conf = new ScallopConf(args) {
      val apples = opt[Int]("apples")
      verify()
    }
    println(conf.apples())
  }
}
```
runs fine using `scallopJVM/run -a 42`, but [fails to link](https://pastebin.com/FLjfbxJS) using `scallopNative/run -a 42`.

Some general classes are missing from Scala Native (like `java.io.Console`), but the worst is the fact that Scala Native misses all the reflection capabilities, both java and scala (they [plan to implement it](https://github.com/scala-native/scala-native/issues/159), but it is still early).

Scallop relies heavily on reflection, thus porting it to scala-native will probably require much more effort than simply cross-compiling.

Currently reflection is used in two places:

* ScallopConf option name guessing - it queries object method names and calls them via reflection to get  val names ([ScallopConf.scala:630](https://github.com/scallop/scallop/blob/develop/src/main/scala/org.rogach.scallop/ScallopConf.scala#L630)). We can remove this functionality from native build, while keeping it in jvm version.
* TypeTags for option type checking. This dates back to the times when there was immutable type-unsafe builder, which needed to check that user requested the proper type when getting option value. This probably can be removed - we can remove `Scallop` class altogether, since everybody is using `ScallopConf` anyway (but this will require bump of the major version to signal incompatibility).

**Comment by Rogach** [comment]
Remaining compatibility errors are fixed by temporarily dropping colored output from native version, and not including some option converters (URL, Path).

**Comment by Rogach** [comment]
I successfully removed TypeTag usage.

I took the liberty of pushing onto your branch, so that we can both test and iterate in this PR.

**Comment by edude03** [comment]
Off topic, but any chance this would work on ScalaJS as well?

**Comment by Rogach** [comment]
@edude03 I think I will be able to do that. Can you please open the separate issue for it?

**Comment by Rogach** [comment]
@oker1 Now native build seems to be linking and running - to test it try running
```
sbt scallopJVM/test
sbt scallopNative/test:run
```

If everything is OK, I'll merge and release it tomorrow.

**Comment by oker1** [comment]
Thanks for picking this up!

**Pull request merged**
