### PR TITLE
Scala 2.13.0-M4

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by Rogach** [comment]
I believe we should wait until scalatest is released for 2.13.0-M4, to release a properly tested version.

Compiler gives a truckload of deprecated procedure syntax warnings for generated code:

```
[warn] /home/travis/build/scallop/scallop/jvm/target/scala-2.13.0-M4/src_managed/main/org/rogach/scallop/ScallopConfValidations.scala:44:139: procedure syntax is deprecated: instead, add `: Unit =` to explicitly declare `validate`'s return type
[warn]   def validate[A1, A2, A3](o1: ScallopOption[A1], o2: ScallopOption[A2], o3: ScallopOption[A3])(fn: (A1, A2, A3) => Either[String, Unit]) {
```

Can you please fix those as well? ([ScallopConfValidations.template](https://github.com/scallop/scallop/blob/develop/src/main/boilerplate/org/rogach/scallop/ScallopConfValidations.template))

**Comment by xuwei-k** [comment]
> Can you please fix those as well? (ScallopConfValidations.template)

https://github.com/scallop/scallop/pull/167

**Comment by Rogach** [comment]
Thanks!

**Comment by Rogach** [comment]
scalatest was released for M4: https://github.com/scalatest/scalatest/issues/1367#issuecomment-397667113

Can you please try testing with it?

**Comment by Rogach** [comment]
For some reason I did not get notification of new changes, and this sat in the queue for so long. Thanks for the PR!

**Pull request merged**
